"""
Stub file for GModule. Autogenerated with gi-stubgen.
"""

import typing as _T  # noqa
from enum import Enum

from gi.repository import GLib


class ModuleFlags(Enum):
    """
    Flags passed to g_module_open().
    Note that these flags are not supported on all platforms.
    """
    LAZY = 1
    LOCAL = 2
    MASK = 3



